rshift = { ">" }
lshift = { "<" }
inc = { "+" }
dec = { "-" }
read = { "," }
write = { "." }
loopbegin = { "[" }
loopend = { "]" }

token = _{ rshift | lshift | inc | dec | read | write | loopbegin | loopend }
tokens = { (token)+ }
//empty = _{ "" }
//COMMENT = _{ "//" ~ (!"\n" ~ ANY)+ }
ignore = _{ !(token) }
grammar = _{ tokens | ignore }
WHITESPACE = _{ " " | "\t" | "\r" | "\n" }
main = _{ SOI ~ tokens ~ EOI }