name: Release

on:
  release:
    types:
      - published

env:
  CARGO_PUBLISH_TOKEN: ${{ secrets.CARGO_PUBLISH_TOKEN }}

jobs:
  DryRun:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo publish --dry-run --token ${CARGO_PUBLISH_TOKEN}

  Release:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    needs: DryRun
    steps:
      - run: echo 'ok!'
